#!/bin/bash
#
# Install zsh and set up Prezto
set -e

# Infer compsys directory
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIR="$(dirname "$(dirname "${DIR}")")"  # This file is 2 levels deep.

echo "Installing zsh..."
sudo apt-get -y -qq install zsh

echo "Installing Prezto..."
if [[ ! -d "${HOME}/.zprezto" ]]; then
  prezto_git=https://github.com/sorin-ionescu/prezto.git
  git clone -q --recursive "${prezto_git}" ~/.zprezto
fi

echo "Setting up .zshrc..."
if [[ ! -f "${HOME}/.zshrc" ]]; then
  cp "${DIR}/setup/zsh/zshrc" "${HOME}/.zshrc"
fi

if [[ ! -f "${HOME}/.zpreztorc" ]]; then
  if [[ -L "${HOME}/.zpreztorc" ]]; then
    rm -f "${HOME}/.zpreztorc"
  fi
  ln -s "${DIR}/setup/zsh/zpreztorc" "${HOME}/.zpreztorc"
fi

echo "Setting up Fasd..."
if ! dpkg -l | grep -q fasd; then
  sudo apt-get install -y -qq fasd
fi

echo "Switching default login shell..."
if [[ ${SHELL##*/} != "zsh" ]]; then
  sudo sed -i -e "s/$(whoami):\\/bin\\/bash/$(whoami):\\/usr\\/bin\\/zsh/" \
    /etc/passwd
fi

echo "Done."
