#!/bin/bash

echo 'INSTALLING ZSHELL'
sudo apt-get install zsh

echo 'INSTALLING ZSPREZTO'
if [ ! -d ~/.zprezto ]
then
	git clone --recursive https://github.com/sorin-ionescu/prezto.git ~/.zprezto
fi

echo 'SETTING UP RC FILES'
if [ ! -f ~/.zshrc ]
then
	cp $ROBOTIC_PATH/compsys/setup/zsh/zshrc ~/.zshrc
fi
if [ ! -f ~/.zpreztorc ]
then
	ln -s $ROBOTIC_PATH/compsys/setup/zsh/zpreztorc ~/.zpreztorc
fi

echo 'SWITCHING DEFAULT SHELL'
if [ $SHELL != '/bin/zsh' ]
then
	chsh -s /bin/zsh
fi

echo 'DONE'
echo
