#!/bin/bash

# Connecting to robot
alias robot='mosh robotics@10.0.0.1'
alias robotx='ssh -Y robotics@10.0.0.1'

# Bagging
alias bag='python ${ROBOTIC_PATH}/compsys/scripts/bag/Bagger.py'
alias bag_merge='python ${ROBOTIC_PATH}/compsys/scripts/bag/Merger.py'

# Monitoring
alias glances='glances -yet 5'
alias main='tmux attach -t MAIN || tmux new -s MAIN'
