#!/bin/bash
#
# Initialize McGill Robotics aliases and functions

# Connecting to robot
alias robosh='mosh robotics@10.0.0.1'
alias robotx='ssh -Y robotics@10.0.0.1'

# Bagging
alias bag='python -m bag.run'

# Monitoring
alias glances='glances -t 5'

# Tmux
alias main='tmux new-session -t MAIN || tmux new -s MAIN'
alias killmain='tmux kill-session -t MAIN'

# Fasd
[[ -n $(which fasd_cd) ]] && alias j='fasd_cd'
