#!/bin/bash

# ROBOT OR NOT
echo 'ARE YOU A ROBOT?'
select yn in "YES" "NO"
do
    case $yn in
        YES )   echo 'E: ROBOT NOT YET SUPPORTED'
                exit;;
        NO )    break;;
    esac
done
echo

# SELECT TEAM
echo 'WHICH TEAM ARE YOU ON?'
select team in "AUV" "ROVER"
do
    case $team in
        AUV )   export ROBOT='auv'
                break;;
        ROVER ) export ROBOT='rover'
                break;;
    esac
done
echo

# ZSHELL INSTALLATION
echo 'WOULD YOU LIKE TO SWITCH FROM BASH TO ZSH?'
echo 'if uncertain, select no'
select yn in "YES" "NO"
do
    case $yn in
        YES )   ./setup/zsh/install
                break;;
        NO )    break;;
    esac
done
echo

# FIGURE OUT ROBOTIC PATH
export ROBOTIC_PATH=`dirname $PWD`

# CLONING REPOSITORY
if [ ! -d $ROBOTIC_PATH/$ROBOT ]
then
    echo 'CLONING REPOSITORY'
    git clone https://github.com/mcgill-robotics/$ROBOT.git $ROBOTIC_PATH/$ROBOT
    echo
fi

# APPEND TO RC FILES
source $ROBOTIC_PATH/compsys/setup/config/install

# GIT HOOKS
source $ROBOTIC_PATH/compsys/setup/hooks/install

# UPDATE
source $ROBOTIC_PATH/compsys/update
