#!/bin/bash

# DETERMINE SHELL
SHELL_EXTENSION=${SHELL##*/}

# ROS
source /opt/ros/indigo/setup.$SHELL_EXTENSION
export ROS_WORKSPACE=$ROBOTIC_PATH/$ROBOT/catkin_ws
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$ROS_WORKSPACE
if [ -s $ROS_WORKSPACE/devel/setup.$SHELL_EXTENSION ]
then
    source $ROS_WORKSPACE/devel/setup.$SHELL_EXTENSION
fi

# CUSTOM ALIASES
source $ROBOTIC_PATH/compsys/aliases
