#!/bin/bash
#
# Initialize McGill Robotics customizations, ROS setup and paths

# Determine shell
_SHELL_PROCESS=$(ps -p $$ -oargs=)
SHELL_EXT=${_SHELL_PROCESS##-}

# Set CLOBBER option to properly source ROS on ZSH
if [[ ${SHELL_EXT} = "zsh" ]]; then
    setopt CLOBBER
fi

# Setup ROS
if [[ -s /opt/ros/jade/setup.${SHELL_EXT} ]]; then
  source /opt/ros/jade/setup.${SHELL_EXT}
fi

function rosconnect {
  if [[ -n "${1}" ]]; then
    export ROS_HOSTNAME=${1}
    export ROS_MASTER_URI=http://${1}:11311
  else
    export ROS_HOSTNAME=
    export ROS_MASTER_URI=http://localhost:11311
  fi
}

function rosworkon {
  if [[ -n "${1}" ]]; then
    if [[ -s ${ROBOTIC_PATH}/${1}/catkin_ws/devel/setup.${SHELL_EXT} ]]; then
      source ${ROBOTIC_PATH}/${1}/catkin_ws/devel/setup.${SHELL_EXT}
    fi
    export ROS_WORKSPACE=${ROBOTIC_PATH}/${1}/catkin_ws
    export ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}:${ROS_WORKSPACE}
  else
    echo "usage: rosworkon <ROBOT>"
    return 1
  fi
}

# Set up default robot
rosworkon ${ROBOT}

# Add compsys scripts to PYTHONPATH
export PYTHONPATH=${PYTHONPATH}:${ROBOTIC_PATH}/compsys/scripts

# Source custom aliases and functions
source ${ROBOTIC_PATH}/compsys/aliases
