#!/bin/bash
#
# Update vim plugins and apt, gem and pip dependencies

#########################################
# Get dependencies from /packages
# Arguments:
#   File in /packages
# Returns:
#   Space separated list of dependencies
#########################################
function get_dependencies () {
  if [[ -s ${ROBOTIC_PATH}/compsys/packages/$1 ]]; then
    cat ${ROBOTIC_PATH}/compsys/packages/$1
  fi
}

echo "Updating apt dependencies..."
get_dependencies apt | xargs sudo apt-get -y -qq install || :

echo "Updating gem dependencies..."
get_dependencies gem | xargs sudo gem install --conservative > /dev/null || :

echo "Updating pip dependencies..."
pip=$(comm -12 --nocheck-order \
  <(pip freeze --local | grep -v '^\-e' | cut -d = -f 1) \
  <(get_dependencies pip))
echo ${pip} | xargs sudo pip install --upgrade > /dev/null || :

echo "Updating pip3 dependencies..."
pip3=$(comm -12 --nocheck-order \
  <(pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1) \
  <(get_dependencies pip3))
echo ${pip3} | xargs sudo pip3 install --upgrade > /dev/null || :

if [[ -d ${HOME}/.vim/bundle/Vundle.vim ]]; then
  echo "Updating vim plugins..."
  vim +PluginInstall +qall
fi

echo "Done."
