#!/bin/bash
#
# Update apt, pip, and pip3 dependencies. Update vim plugins.
#

set -e

if tty -s ; then
  section=$(tput bold; tput setaf 2)
  reset=$(tput sgr0)
else
  section=""
  reset=""
fi

# Infer compsys directory and ROBOTIC_PATH
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROBOTIC_PATH="$(dirname "${DIR}")"

echo "${section}Updating apt dependencies...${reset}"
sudo apt-get -q -y update
# Filter out all comments in the apt requirements file using sed before
# piping the contents of the requirements list into xargs.
sed 's/#.*//' "${DIR}/packages/apt" | xargs sudo apt-get install -y

# Suppress pip version checks.
ROBOTICS_PIP_CONF="${DIR}/setup/config/pip.conf"
USER_PIP_DIR="${HOME}/.config/pip"
USER_PIP_CONF="${USER_PIP_DIR}/pip.conf"
if [[ ! -f "${USER_PIP_CONF}" ]]; then
  echo "${section}Disabling user pip version checks...${reset}"
  mkdir -p "${USER_PIP_DIR}"
  cp "${ROBOTICS_PIP_CONF}" "${USER_PIP_CONF}"
fi
ROOT_PIP_DIR="/root/.config/pip"
ROOT_PIP_CONF="${ROOT_PIP_DIR}/pip.conf"
if [[ ! -f "${ROOT_PIP_CONF}" ]]; then
  echo "${section}Disabling root pip version checks...${reset}"
  sudo mkdir -p "${ROOT_PIP_DIR}"
  sudo cp "${ROBOTICS_PIP_CONF}" "${ROOT_PIP_CONF}"
fi

echo "${section}Updating Python 2 dependencies...${reset}"
sudo -H pip2 install --upgrade --requirement "${DIR}/packages/pip"

# Install/update all scripts.
pushd "${DIR}/scripts"
for package in *; do
  echo "${section}Installing ${package}...${reset}"
  pushd "${package}"
  sudo -H python setup.py install
  popd
done

if [[ -f "${HOME}/.vim/autoload/plug.vim" ]]; then
  echo "${section}Updating vim plugins...${reset}"
  vim +PlugUpgrade +PlugInstall +PlugUpdate +PlugClean +qall
fi

# Update tools.sh repository.
if [[ -d "${ROBOTIC_PATH}/tools.sh" ]]; then
  pushd "${ROBOTIC_PATH}/tools.sh"
  ./update_repo.sh
  popd
fi

# Update Prezto repository.
if [[ -d "${HOME}/.zprezto" ]]; then
  pushd "${HOME}/.zprezto"
  git pull
  git submodule sync --recursive
  git submodule update --init --recursive --force
  popd
fi

echo "Done."
