#!/bin/bash
#
# Update apt, pip, and pip3 dependencies. Update vim plugins.

set -e

section=$(tput bold; tput setaf 2)
reset=$(tput sgr0)

echo "${section}Updating apt dependencies...${reset}"
sudo apt-get -qq update
# Filter out all comments in the apt requirements file using sed before
# piping the contents of the requirements list into xargs.
sed 's/#.*//' "${ROBOTIC_PATH}/compsys/packages/apt" | xargs sudo apt-get install -y

echo "${section}Updating pip dependencies...${reset}"
sudo -H pip install --upgrade --requirement "${ROBOTIC_PATH}/compsys/packages/pip"

echo "${section}Updating pip3 dependencies...${reset}"
sudo -H pip3 install --upgrade --requirement "${ROBOTIC_PATH}/compsys/packages/pip3"

if [[ -d "${HOME}/.vim/bundle/Vundle.vim" ]]; then
  echo "Updating vim plugins..."
  vim +PluginInstall +qall
fi

# Update tools.sh repository.
if [[ -d "${ROBOTIC_PATH}/tools.sh" ]]; then
  pushd "${ROBOTIC_PATH}/tools.sh"
  ./update_repo.sh
  popd
fi

# Update Prezto repository.
if [[ -d "${HOME}/.zprezto" ]]; then
  pushd "${HOME}/.zprezto"
  git pull
  git submodule sync --recursive
  git submodule update --init --recursive --force
  popd
fi

echo "Done."
