#!/bin/bash
#
# Install git hook to update dependencies on pull

hooks=${ROBOTIC_PATH}/compsys/.git/hooks

echo "Setting up git hook..."
if [[ ! -d ${hooks} ]]; then
  mkdir ${hooks}
fi
cp ${ROBOTIC_PATH}/compsys/setup/hooks/post-merge ${hooks}/post-merge
chmod +x ${hooks}/post-merge

echo "Done."
