#!/bin/bash
#
# Set up shell, vim and tmux configuration files
set -e

for rcfile in "${HOME}/.bashrc" "${HOME}/.zshrc"; do
  if [[ -f ${rcfile} ]]; then
    if [[ -z $(grep "export ROBOT=" ${rcfile}) ]]; then
      echo "Updating ${rcfile##*/}..."
      sed -e "s@=\${ROBOT}@=${ROBOT}@" \
        -e "s@=\${IAMROBOT}@=${IAMROBOT}@" \
        -e "s@=\"\${ROBOTIC_PATH}\"@=\"${ROBOTIC_PATH//\//\/}\"@" \
        -e "s@\${rcfile}@~\/${rcfile##*/}@" \
        "${ROBOTIC_PATH}/compsys/setup/config/rc" >> "${rcfile}"
    fi
  fi
done

for rcfile in "vimrc" "tmux.conf"; do
  if [[ ! -f "${HOME}/.${rcfile}" ]]; then
    if [[ -L "${HOME}/.${rcfile}" ]]; then
      echo "Removing broken link..."
      rm -f "${HOME}/.${rcfile}"
    fi
    echo "Adding .${rcfile}..."
    ln -s "${ROBOTIC_PATH}/compsys/setup/config/${rcfile}" "${HOME}/.${rcfile}"
  fi
done

if [[ ! -d "${HOME}/.vim/bundle/Vundle.vim" ]]; then
  echo "Setting up vim bundles..."
  git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  vim +PluginInstall +qall
fi

echo "Done."
