#!/bin/bash

echo 'UPDATING SHELL RC FILES'
for rcfile in "$HOME/.bashrc" "$HOME/.zshrc"
do
    if [ -f $rcfile ]
    then
        if [[ -z `grep "export ROBOT=" $rcfile` ]]
        then
            echo "updating $rcfile"
            echo "
            #
            # MCGILL ROBOTICS PERSONAL CONFIGURATION
            #
            # The following can be personalized to your liking.
            # EDITOR        Your text editor of choice.
            # ROBOT         Team you are working on ('auv' or 'rover').
            # IAMROBOT      If computer will be shared ('true' or 'false').
            # ROBOTIC_PATH  Absolute path to directory containing the local
            #               McGill Robotics git repositories.
            #
            export EDITOR=vim
            export ROBOT=$ROBOT
            export IAMROBOT=$IAMROBOT
            export ROBOTIC_PATH=$ROBOTIC_PATH
            source "'$ROBOTIC_PATH'"/compsys/roboticrc
            " >> $rcfile
        fi
    fi
done

echo 'ADDING OTHER CONFIGURATION FILES'
for rcfile in "vimrc" "tmux.conf"
do
    if [ ! -f $HOME/.$rcfile ]
    then
        echo "adding $HOME/.$rcfile"
        ln -s $ROBOTIC_PATH/compsys/setup/config/$rcfile $HOME/.$rcfile
    fi
done

echo 'SETTING UP VIM FOR USE'
if [ ! -d $HOME/.vim/bundle/Vundle.vim ]
then
    git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi
vim +PluginInstall +qall

echo 'DONE'
echo
