#!/bin/bash
#
# Install ROS Kinetic Kame on Ubuntu 16.04 LTS

echo "Adding ROS PPA..."
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu xenial main" \
  > /etc/apt/sources.list.d/ros-latest.list'

echo "Getting ROS apt verification key..."
sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 \
  --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116

echo "Updating apt package list..."
sudo apt-get -qq update

echo "Installing ROS..."
sudo apt-get -y install ros-kinetic-desktop-full python-rosinstall

echo "Setting up ROS dependencies..."
sudo rosdep init
rosdep update

echo "Done."
