#!/bin/bash
#
# Install ROS Kinetic Kame on Ubuntu 16.04 LTS
set -e

OS_VERSION=$(lsb_release -sc)

if [[ ${OS_VERSION} == "xenial" ]]; then
  ROS_VERSION="kinetic"
elif [[ ${OS_VERSION} == "bionic" ]]; then
  ROS_VERSION="melodic"
else
  echo "Unknown OS detected, installation aborted!"
  exit -1
fi

echo "Adding ROS PPA..."
ros_ppa_cmd="echo 'deb http://packages.ros.org/ros/ubuntu ${OS_VERSION} main'"
ros_ppa_cmd="${ros_ppa_cmd} > /etc/apt/sources.list.d/ros-latest.list"
sudo sh -c "${ros_ppa_cmd}"

echo "Getting ROS apt verification key..."
servers=(
  "hkp://ha.pool.sks-keyservers.net:80"
  "hkp://pgp.mit.edu:80"
  "hkp://keyserver.ubuntu.com:80"
)
for server in "${servers[@]}"; do
  # Try each valid keyserver until the first succeeds
  sudo apt-key adv --keyserver "${server}" \
    --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116 \
    && break
done

echo "Updating apt package list..."
sudo apt-get -qq update

echo "Installing ROS..."
sudo apt-get -y install ros-${ROS_VERSION}-desktop-full python-rosinstall

echo "Setting up ROS dependencies..."
if [[ ! -e /etc/ros/rosdep/sources.list.d/20-default.list ]]; then
  sudo rosdep init
fi
rosdep update

echo "Done."
